import dev.touchxbox.pad.*;
public final class LayoutTest {
    static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
    public static void main(String[] a){
        LayoutProfile p=new LayoutProfile();
        for(float[] dims:new float[][]{{2560,1532},{1600,2492},{2705,1121},{1260,2705}}){boolean wide=dims[0]>dims[1];check(p.foldConflict(wide,dims[0],dims[1])==null,"Default fold must not cover controls");for(LayoutProfile.Spec s:LayoutProfile.SPECS){LayoutProfile.Box b=p.page(wide).box(s,dims[0],dims[1]);check(b.x>=0&&b.y>=0&&b.x+b.w<=dims[0]+.01&&b.y+b.h<=dims[1]+.01,"Control in bounds");}}
        p.landscape.foldX=.12f;p.landscape.foldY=.49f;check("L".equals(p.foldConflict(true,2560,1532)),"Reject fold/fixed stick conflict");p.leftFloating=true;check(p.foldConflict(true,2560,1532)==null,"Floating origin is not a fixed occupied control");
        p.landscape.move("FOLD",-1,2,2560,1532);LayoutProfile.Box f=p.landscape.fold(2560,1532);check(f.x==0&&Math.abs(f.y+f.h-1532)<.01,"Fold clamps to screen");
        check(!p.rightFloating&&p.portrait.items.get("L").x==.12f,"Directions and stick modes independent");
        StickGesture g=new StickGesture();g.begin(850,400,850,400,100,12,1000);check(g.x==0&&g.y==0,"Dynamic center equals touch point");check(!g.hold(1499)&&g.hold(1500)&&!g.hold(1501),"Single long press after 500ms");g.move(950,400);check(g.clicked&&Math.abs(g.x-1)<.001,"Hold survives later drag");g.end();check(!g.active&&!g.clicked&&g.x==0&&g.y==0&&!g.hold(9999),"Release/cancel clears click and axes");
        g.begin(500,500,500,500,100,12,0);g.move(514,500);g.move(500,500);check(!g.hold(5000),"Dragging away then back must not synthesize L3");
        g.begin(100,100,100,100,100,12,0);g.move(1100,1100);check(Math.abs(Math.hypot(g.x,g.y)-1)<.001,"Diagonal clipped radially");g.end();g.begin(900,700,900,700,100,12,8000);check(g.x==0&&g.y==0&&!g.clicked,"New touch gets a fresh center");
        ButtonChord chord=new ButtonChord();chord.point(0,.5f,.8f);chord.point(1,.5f,.85f);check(chord.mask()==1<<PadState.A,"Two touches one triangle");chord.up(0);check(chord.mask()==1<<PadState.A,"Release one finger preserves other");chord.point(2,.2f,.5f);check(chord.mask()==((1<<PadState.A)|(1<<PadState.X)),"Independent triangle chord");chord.point(1,.8f,.5f);check(chord.mask()==((1<<PadState.B)|(1<<PadState.X)),"Sliding switches triangle");chord.point(1,1.2f,.5f);chord.point(2,.5f,.5f);check(chord.mask()==0,"Outside and center release");chord.point(0,.5f,.2f);check(chord.mask()==1<<PadState.Y,"Top triangle Y");chord.reset();check(chord.mask()==0,"Cancel clears chord");
        p.abxyStyle=1;check(p.visible(LayoutProfile.spec("ABXY"))&&!p.visible(LayoutProfile.spec("A")),"Compound replaces separate keys");p.abxyStyle=0;check(!p.visible(LayoutProfile.spec("ABXY"))&&p.visible(LayoutProfile.spec("A")),"Separate buttons restored");
        for(boolean ab:new boolean[]{false,true})for(boolean xy:new boolean[]{false,true}){p.swapAB=ab;p.swapXY=xy;int[] from={PadState.A,PadState.B,PadState.X,PadState.Y};int[] expected={ab?PadState.B:PadState.A,ab?PadState.A:PadState.B,xy?PadState.Y:PadState.X,xy?PadState.X:PadState.Y};for(int i=0;i<4;i++){check(p.mapButton(from[i])==expected[i],"Independent face-button permutation");check(p.mapButton(p.mapButton(from[i]))==from[i],"Swapping twice restores input");}chord.reset();chord.point(0,.5f,.8f);chord.point(1,.5f,.9f);chord.point(2,.2f,.5f);check(p.mapFaceMask(chord.mask())==((1<<expected[0])|(1<<expected[2])),"Mapped multi-finger chord");chord.up(0);check((p.mapFaceMask(chord.mask())&(1<<expected[0]))!=0,"Mapped shared button remains held");chord.up(1);check(p.mapFaceMask(chord.mask())==(1<<expected[2]),"Mapped independent release");chord.reset();check(p.mapFaceMask(chord.mask())==0,"Mapped cancel releases all");check(p.mapButton(PadState.LB)==PadState.LB&&p.mapButton(PadState.START)==PadState.START,"Other buttons unaffected");check(p.label(LayoutProfile.spec("A")).equals(ab?"B":"A")&&p.label(LayoutProfile.spec("X")).equals(xy?"Y":"X"),"Separate labels match mapped events");}
        check(LayoutProfile.spec("LB").h==55&&LayoutProfile.spec("RB").h==55,"Bumper heights unchanged");check(LayoutProfile.spec("LT").w==LayoutProfile.spec("LB").w&&LayoutProfile.spec("RT").h>LayoutProfile.spec("RB").h,"Only triggers become taller");
        LayoutProfile fresh=new LayoutProfile();for(float[] dims:new float[][]{{2560,1520},{1600,2480},{2705,1121}}){LayoutProfile.Page page=fresh.page(dims[0]>dims[1]);for(String[] side:new String[][]{{"LT","LB"},{"RT","RB"}}){LayoutProfile.Box top=page.box(LayoutProfile.spec(side[0]),dims[0],dims[1]),bottom=page.box(LayoutProfile.spec(side[1]),dims[0],dims[1]);check(Math.abs(top.x-bottom.x)<.01&&top.y+top.h<bottom.y,"Shoulder stack does not overlap");}for(String key:new String[]{"VIEW","XBOX","MENU"}){LayoutProfile.Box b=page.box(LayoutProfile.spec(key),dims[0],dims[1]);check(Math.abs(b.y+b.h-dims[1])<.01,"System keys at bottom");}}
        LayoutProfile.Page page=fresh.landscape;page.shoulderWidth=.8f;page.triggerHeight=1.4f;page.bumperHeight=.7f;page.items.get("RB").scale=1.6f;for(String key:new String[]{"LT","RT","LB","RB"}){LayoutProfile.Box b=page.box(LayoutProfile.spec(key),960,490);check(Math.abs(b.w-51.2f)<.01,"All four widths linked even with legacy per-button scaling");check(Math.abs(b.h-(key.endsWith("T")?120.4f:38.5f))<.01,"Heights linked in independent trigger and bumper pairs");}check(fresh.portrait.shoulderWidth==1&&fresh.portrait.triggerHeight==1,"Linked dimensions remain independent by orientation");
        for(float[] corner:new float[][]{{.02f,.02f},{.98f,.02f},{.98f,.98f},{.02f,.98f}})check(ButtonChord.triangle(corner[0],corner[1])==-1,"Octagon cutout is not a face-button hit");check(ButtonChord.triangle(.5f,.01f)==PadState.Y&&ButtonChord.triangle(.99f,.5f)==PadState.B,"Octagon edge belongs to corresponding sector");
        LayoutProfile delete=new LayoutProfile();LayoutProfile.Spec key1=delete.addKey(4),key2=delete.addKey(26);delete.landscape.keyboardScale=1.25f;delete.landscape.items.get(key2.name).scale=.6f;check(delete.landscape.box(key1,960,490).w==95&&delete.landscape.box(key2,960,490).w==95,"Keyboard size shared independent of individual legacy scales");delete.hiddenButtons.add("L");delete.leftFloating=true;check(!delete.visible(LayoutProfile.spec("L"))&&!delete.floating(LayoutProfile.spec("L")),"Removed floating stick creates no input surface");delete.hiddenButtons.add("A");check(delete.mapFaceMask(1<<PadState.A)==0,"Removed face sector sends no input");delete.swapAB=true;check(delete.mapFaceMask(1<<PadState.B)==0&&delete.mapFaceMask(1<<PadState.A)==(1<<PadState.B),"Hidden logical button survives swapping");delete.hiddenButtons.remove("L");check(delete.floating(LayoutProfile.spec("L")),"Restoring stick preserves floating setting");
        LayoutProfile excluded=new LayoutProfile();LayoutProfile.Box region=excluded.landscape.fold(2560,1520);check(excluded.inFoldRegion(1200,region.y+region.h/2,2560,1520)&&excluded.inFoldRegion(1400,region.y+region.h/2,2560,1520),"Both screen halves honor the same fold exclusion");check(!excluded.inFoldRegion(region.x-1,region.y,2560,1520),"Outside fold region remains available");
        StickGesture throttle=new StickGesture(true);check(throttle.x==0&&throttle.y==1,"FPV starts at the bottom with centered yaw");throttle.begin(100,100,300,300,100,12,0);check(throttle.y==1,"Fixed throttle down does not jump to touch height");throttle.move(100,25);check(Math.abs(throttle.y-.25f)<.001,"FPV vertical drag starts from previous throttle");throttle.end();check(throttle.x==0&&Math.abs(throttle.y-.25f)<.001,"Release centers only yaw");throttle.begin(800,700,800,700,100,12,1000);check(throttle.x==0&&Math.abs(throttle.y-.25f)<.001,"New floating origin preserves throttle");throttle.move(900,700);check(throttle.x==1&&Math.abs(throttle.y-.25f)<.001,"Full yaw cannot change held throttle");throttle.move(900,575);check(throttle.x==1&&throttle.y==-1,"Radio axes clamp independently at full throttle and yaw");throttle.end();throttle.begin(200,200,200,200,100,12,2000);check(throttle.y==-1&&throttle.hold(2500),"Retained throttle still supports long press");throttle.end();check(!throttle.clicked&&throttle.y==-1,"Throttle release releases click only");throttle.reset();check(throttle.y==1&&throttle.x==0,"Suspending input returns throttle to minimum");
        LayoutProfile skin=new LayoutProfile();skin.protocol=ControllerProtocol.SWITCH_PRO;check(skin.label(LayoutProfile.spec("A")).equals("B")&&skin.label(LayoutProfile.spec("Y")).equals("X")&&skin.label(LayoutProfile.spec("LT")).equals("ZL"),"NS names match wire button positions");skin.protocol=ControllerProtocol.DS4;check(skin.label(LayoutProfile.spec("A")).equals("×")&&skin.label(LayoutProfile.spec("Y")).equals("△"),"PS face symbols");skin.labels.put("A",new String[]{"自定","亮"});check(skin.label(LayoutProfile.spec("A")).equals("自定"),"Protocol skin preserves custom names");skin.protocol=ControllerProtocol.FPV;check(skin.throttle(LayoutProfile.spec("L"))&&!skin.throttle(LayoutProfile.spec("R"))&&skin.label(LayoutProfile.spec("CH6")).equals("CH6")&&!skin.visible(LayoutProfile.spec("A"))&&!skin.visible(LayoutProfile.spec("LT"))&&skin.visible(LayoutProfile.spec("CH7")),"Only FPV left stick holds throttle");
        System.out.println("LayoutTest passed: bounds, styles, protocol labels, retained FPV throttle, shared keyboard sizing, deletion and restoration");
    }
}
