import dev.touchxbox.pad.*;
/** Run on Android's JSON implementation with app_process, not an SDK stub jar. */
public final class LayoutRoundTripTest {
    static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
    public static void main(String[] args){
        LayoutProfile p=new LayoutProfile();p.name="平板布局";p.leftFloating=true;p.rightFloating=false;p.leftTriggerClick=true;p.rightTriggerClick=false;p.dpadStyle=2;p.abxyStyle=1;p.opacity=.25f;p.landscape.items.get("ABXY").scale=1.23f;p.portrait.foldX=.3f;
        LayoutProfile q=LayoutStore.decode(LayoutStore.encode(p));check(q.name.equals(p.name)&&q.id.equals(p.id),"Unicode name and identity");check(q.leftFloating&&!q.rightFloating&&q.leftTriggerClick&&!q.rightTriggerClick,"Independent styles");check(q.dpadStyle==2&&q.abxyStyle==1&&q.opacity==.25f,"Persist component styles");check(q.landscape.items.get("ABXY").scale==1.23f&&q.portrait.foldX==.3f,"Both orientations");q.landscape.items.get("ABXY").x=.2f;check(p.landscape.items.get("ABXY").x!=.2f,"Isolated draft");
        for(boolean ab:new boolean[]{false,true})for(boolean xy:new boolean[]{false,true}){p.swapAB=ab;p.swapXY=xy;q=LayoutStore.decode(LayoutStore.encode(p));check(q.swapAB==ab&&q.swapXY==xy,"Each swap combination round trips independently");}
        LayoutProfile old=LayoutStore.decode("{\"version\":2,\"name\":\"old\",\"leftFloating\":true,\"landscape\":{\"items\":{\"LB\":{\"x\":0.3,\"y\":0.4,\"scale\":1.2}}}}");check(old.leftFloating&&old.abxyStyle==0&&old.dpadStyle==0&&!old.rightTriggerClick&&!old.swapAB&&!old.swapXY,"Old template migration");check(old.landscape.items.get("LB").x==.3f&&old.landscape.items.get("LB").y==.4f&&old.landscape.items.get("LB").scale==1.2f,"Existing custom positions and sizes retained");
        check(old.landscape.bumperHeight==1.2f,"Old bumper height migrates into the paired setting");
        check(old.landscape.unitRatio==0,"Legacy files wait for their first device to capture the missing size basis");
        p.landscape.ensureRelativeSize(2844,1260);p.portrait.ensureRelativeSize(1260,2844);
        q=TemplateCode.decode(TemplateCode.encode(p));check(q.landscape.unitRatio==p.landscape.unitRatio&&q.portrait.unitRatio==p.portrait.unitRatio,"Both size ratios survive the portable string");
        check(!q.landscape.ensureRelativeSize(2560,1600),"Import on a tablet cannot replace the phone size ratio");
        LayoutProfile.Box phone=p.landscape.box(LayoutProfile.spec("ABXY"),2844,1260),tablet=q.landscape.box(LayoutProfile.spec("ABXY"),2560,1600);
        check(Math.abs(tablet.w/phone.w-1600f/1260)<.00001f&&Math.abs(tablet.h/phone.h-1600f/1260)<.00001f,"Copy/import scales both dimensions proportionally across aspect ratios");
        p.landscape.shoulderWidth=.8f;p.landscape.triggerHeight=1.4f;p.landscape.bumperHeight=.7f;p.portrait.shoulderWidth=1.2f;
        q=LayoutStore.decode(LayoutStore.encode(p));check(q.landscape.shoulderWidth==.8f&&q.landscape.triggerHeight==1.4f&&q.landscape.bumperHeight==.7f&&q.portrait.shoulderWidth==1.2f,"Independent linked dimensions survive storage");
        String code=TemplateCode.encode(p);q=TemplateCode.decode("  "+code+"\n");check(!q.id.equals(p.id)&&q.name.equals(p.name),"Imported copy gets a fresh identity");check(q.swapAB&&q.swapXY&&q.dpadStyle==2&&q.abxyStyle==1&&q.leftFloating&&!q.rightFloating,"Imported copy retains styles and swaps");check(q.landscape.triggerHeight==1.4f&&q.landscape.bumperHeight==.7f&&q.portrait.shoulderWidth==1.2f,"Linked dimensions export/import");check(q.landscape.items.get("ABXY").scale==1.23f&&q.portrait.foldX==.3f,"Positions and fold region export/import");
        for(String invalid:new String[]{"","random","TXPAD1:%%%%",code.substring(0,code.length()-12),"TXPAD1:"+new String(new char[90001]).replace('\0','A')}){boolean rejected=false;try{TemplateCode.decode(invalid);}catch(IllegalArgumentException e){rejected=true;}check(rejected,"Invalid or truncated import rejected");}
        LayoutProfile.Spec key=p.addKey(26);p.labels.put(key.name,new String[]{"前进","前进中"});p.labels.put("A",new String[]{"跳跃","起跳"});p.labels.put("D_0",new String[]{"上","上移"});p.landscape.items.get(key.name).x=.44f;p.portrait.items.get(key.name).scale=1.3f;p.toggleLabels.add(key.name);p.highlighted.add(key.name);p.landscapeOnly=true;p.landscape.keyboardScale=.75f;p.portrait.keyboardScale=1.25f;
        for(int protocol=0;protocol<ControllerProtocol.NAMES.length;protocol++){p.protocol=protocol;q=TemplateCode.decode(TemplateCode.encode(p));check(q.protocol==protocol&&q.keyboard.size()==1&&q.keyboard.get(0).code==26,"Every protocol and keyboard mapping exported");check(q.label(q.keyboard.get(0)).equals("前进")&&q.label(q.keyboard.get(0),true).equals("前进中"),"Up/down names exported independently");check(q.labels.get("A")[1].equals("起跳")&&q.directionLabel(0,true).equals("上移"),"Gamepad/dpad names survive swaps and import");check(q.landscape.items.get(key.name).x==.44f&&q.portrait.items.get(key.name).scale==1.3f,"Keyboard geometry in both orientations");check(q.keyboard.get(0).code==26&&q.mapButton(PadState.B)==PadState.A,"Changing labels does not change functionality");}
        p.landscape.items.get(key.name).width=74;p.landscape.items.get(key.name).height=45;p.portrait.items.get(key.name).width=70;p.portrait.items.get(key.name).height=45;
        q=TemplateCode.decode(TemplateCode.encode(p));check(q.landscape.items.get(key.name).width==74&&q.landscape.items.get(key.name).height==45&&q.portrait.items.get(key.name).width==70,"Preset dimensions survive copy and both orientations");
        q.removeKey(key.name);check(q.keyboard.isEmpty()&&!q.labels.containsKey(key.name)&&!q.landscape.items.containsKey(key.name),"Deleting keyboard button clears only its data");
        q=TemplateCode.decode(TemplateCode.encode(p));check(q.landscapeOnly&&q.toggleLabels.contains(key.name)&&q.highlighted.isEmpty(),"Orientation and highlight option saved; visual session state not exported");check(q.landscape.keyboardScale==.75f&&q.portrait.keyboardScale==1.25f,"Shared keyboard size by orientation");q.activateLabel(key.name);check(q.highlighted.contains(key.name),"First tap highlights");q.activateLabel(key.name);check(!q.highlighted.contains(key.name),"Second tap clears highlight");q.activateLabel("A");check(!q.highlighted.contains("A"),"Normal buttons do not latch visual state");
        p.hiddenButtons.add("LT");p.hiddenButtons.add("A");q=TemplateCode.decode(TemplateCode.encode(p));check(q.hiddenButtons.contains("LT")&&q.hiddenButtons.contains("A")&&q.landscape.items.get("LT").x==p.landscape.items.get("LT").x,"Deleted controller controls and their restoration geometry persist");
        p.protocol=ControllerProtocol.FPV;p.hiddenButtons.add("CH6");p.landscape.items.get("CH7").x=.19f;p.labels.put("CH7",new String[]{"模式","模式已切换"});q=TemplateCode.decode(TemplateCode.encode(p));check(!q.visible(LayoutProfile.spec("CH6"))&&q.visible(LayoutProfile.spec("CH7"))&&q.landscape.items.get("CH7").x==.19f&&q.label(LayoutProfile.spec("CH7")).equals("模式"),"FPV auxiliary selection, geometry and names import");q.protocol=ControllerProtocol.XBOX;check(!q.visible(LayoutProfile.spec("CH7"))&&!q.visible(LayoutProfile.spec("LT")),"Switching protocol preserves hidden gamepad controls without exposing radio auxiliaries");
        check(old.holdsOutside(LayoutProfile.spec("LT"))&&old.holdsOutside(LayoutProfile.spec("RB"))&&!old.holdsOutside(LayoutProfile.spec("A")),"Legacy templates inherit shoulder-only retention");
        p.holdOutside.clear();p.holdOutside.add(key.name);p.holdOutside.add("ABXY");p.landscape.setShoulderLayout(2,2844,1260);p.landscape.move("RT",2200f/2844,400f/1260,2844,1260);p.portrait.setShoulderLayout(1,1260,2844);
        q=TemplateCode.decode(TemplateCode.encode(p));check(q.holdOutside.equals(p.holdOutside)&&!q.holdsOutside(LayoutProfile.spec("LT")),"Explicit shoulder off and keyboard/chord on survive portable copy");
        check(q.landscape.shoulderLayout==2&&q.portrait.shoulderLayout==1&&q.landscape.shoulderX==p.landscape.shoulderX&&q.landscape.shoulderY==p.landscape.shoulderY,"Independent orientation shoulder links and anchors survive export");
        p.holdOutside.clear();q=TemplateCode.decode(TemplateCode.encode(p));check(q.holdOutside.isEmpty(),"Explicit empty array does not re-enable defaults");
        boolean badHold=false;try{LayoutStore.decode("{\"holdOutside\":[\"L\"]}");}catch(IllegalArgumentException e){badHold=true;}check(badHold,"Stick cannot import momentary-button retention");
        check(old.fpvMode==FpvMode.AMERICAN,"Legacy templates keep current American mode");
        p.protocol=ControllerProtocol.FPV;
        for(int mode:new int[]{FpvMode.AMERICAN,FpvMode.JAPANESE,FpvMode.CHINESE}){p.fpvMode=mode;q=TemplateCode.decode(TemplateCode.encode(p));check(q.fpvMode==mode,"FPV mode survives copy/import");check(q.throttle(LayoutProfile.spec(mode==FpvMode.AMERICAN?"L":"R")),"Imported mode preserves throttle side");}
        check(LayoutStore.decode("{\"fpvMode\":99}").fpvMode==FpvMode.AMERICAN,"Invalid FPV mode uses safe default");
        System.out.println("PASS: template migration and portable round trip; protocols and FPV auxiliary channels, keyboard mappings/shared sizes, names, optional highlight, orientation gating, hidden controls, malformed-input rejection");
    }
}
